### ISSUE TITLE
Very nice Control but issues when using UIPageViewController

### ISSUE THREAD

**Issue by waelsaad** [mohn93/AdvancedPageControl#3]
I really like this control but I had some issues trying to animate to the right index of the control when I am using a UIPageViewController

So this is what I did:-

```
        if let scrollView = self.view.subviews.first(where: { $0 is UIScrollView }) as? UIScrollView {
            scrollView.delegate = self
        }
```

```
extension OnBoardingPageController: UIScrollViewDelegate {
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        let offSet = scrollView.contentOffset.x
        let width = scrollView.frame.width
        print(offSet, width)

        pageControl.setCurrentItem(offset: CGFloat(offSet),
                                   width: CGFloat(width))
    }
}
```

With the UICollectionView example, the width keeps on increasing but with UIPageViewController its constant.

**Comment by mohn93** [comment]
Thanks for trying this, actually page controller current offset is not meant to be tracked like this, 

But I have a workaround that might work for you:
first, you'll have to put an index for every view controller, in member variable or a view tag, and then you have to implement this method in the page controller delegate 

```
  func pageViewController(_ pageViewController: UIPageViewController, didFinishAnimating finished: Bool, previousViewControllers: [UIViewController], transitionCompleted completed: Bool)
    {
       if (!completed)
      {
        return
      }
        self.pendingIndex = (pageViewController.viewControllers?.first as! ContentView).itemIndex //Page Index
    }
```
Then in the scrollview delegate method that you mentioned above do the following
```
 func scrollViewDidScroll(_ scrollView: UIScrollView) {
        
        let width = scrollView.frame.width
        let offSet = scrollView.contentOffset.x + (width*CGFloat(pendingIndex ?? 0)) - width

        pageControl.setCurrentItem(offset: CGFloat(offSet),
                                   width: CGFloat(width))
    }
```

Then your good to go, tell me what happens with you.

**Comment by waelsaad** [comment]
Just perfect. It worked flawlessly. :]. It would be nice if you get to have time to add more transitions it would be really nice.  Thank you so much for your help.
