### ISSUE TITLE
When Extended page control added in a container in storyboard. It doesn't work correctly.

### ISSUE THREAD

**Issue by amit2908** [mohn93/AdvancedPageControl#4]
We need to keep the extended page control directly on the main view.

**Comment by mohn93** [comment]
I couldn't understand you can you clarify more

**Comment by arensade** [comment]
I have a same problem. You can add **UIPageControl** in your storyboard and then change UIPageControl class to any suit custom class that you want but I think it's not initialing in runtime when you change it to **AdvancedPageControl**.
