### ISSUE TITLE
ExtendedDot currentPageIndicatorTintColor

### ISSUE THREAD

**Issue by tanvi-dev** [mohn93/AdvancedPageControl#5]
I want to set currentPageIndicatorTintColor for ExpandedDot, can you help?

**Comment by Mina-Gerges** [comment]
I face the same issue here, did you find a solution for it?

My problem is that all dots have the same color whether it's selected or not.

**Comment by socheat-leang** [comment]
@Mina-Gerges  It's what I have faced on. Anyone here have solution with this?

**Comment by mohn93** [comment]
Guys sorry about the delay, I'm releasing a Fix version:

🚀  AdvancedPageControl (0.1.5) successfully published

Please test and give your feedback

**Comment by Mina-Gerges** [comment]
Thanks a lot. It's working fine now.
