### ISSUE TITLE
How can i resize, change tincolor(currently white only) and other properties outside of your class (from my viewcontroller ) ? 

### ISSUE THREAD

**Issue by jams032** [mohn93/AdvancedPageControl#7]
Hi, the demo is nice. I was going to use this in my app. But the problem is I want to change the color, size, and others from my view controller. 

 pageControl8.drawer = ThinWormDrawer()
 pageControl8.drawer = ScaleDrawer(numberOfPages:5,
                                          height: 16,
                                          width: 16,
                                          space: 16,
                                          raduis: 16,
                                          currentItem: 0,
                                          indicatorColor: .red,
                                          dotsColor:  .lightGray) // when i apply this, UI become distored. 

I can not do it properly, could you please help me?

**Comment by mohn93** [comment]
@jams032, Thanks for trying this out, 

I tried this code it works as expected, can you please make sure that you are on the last update v0.1.7
