### ISSUE TITLE
[ExtendedDotDrawer] The indicator overlap other items

### ISSUE THREAD

**Issue by longhoang2984** [mohn93/AdvancedPageControl#8]
I have a problem when updating the current page, the indicator view overlap with other dot items

`newPageControler.drawer = ExtendedDotDrawer(numberOfPages: 3,space: 16.0, indicatorColor: SColors.greenButton.color, dotsColor: SColors.mainGray.color, isBordered: false, borderWidth: 0.0, indicatorBorderColor: .clear, indicatorBorderWidth: 0.0)`

![Simulator Screen Shot - iPhone 11 Pro Max - 2021-03-19 at 01 21 36](https://user-images.githubusercontent.com/11419002/111677122-7ca74e80-8851-11eb-845a-8515263a2351.png)

**Comment by mohn93** [comment]
Thanks for trying this out.

What's ur iOS, and Swift version
